name = "did-c3-alliance-site"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "d90dcd7b745fd3d5fe182073b3f2ad54"

[assets]
directory = "./public"

# Custom Domain (IO-054)
[[routes]]
pattern = "did.c3-alliance.org"
custom_domain = true
