name = "voice-plausiblepotentials"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
SITE_URL = "https://voice.plausiblepotentials.com"

[[kv_namespaces]]
binding = "SESSION"
id = "3bd5d49579eb440e8dc45a790983a091"
